import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/sidebar/app-sidebar";
import { Label } from "@/components/ui/label";

const nunito_sans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Satudua",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito_sans.className} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="p-4 w-full h-full relative">
            <div className="bg-primary p-4 w-full rounded-2xl">
              <Label type="title" className="text-white">Page Name</Label>
            </div>
            <div className="">
              {children}
            </div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
