import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "@/components/layout/app-sidebar";
import AppTitle from "@/components/layout/app-title";

const nunito_sans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Satudua",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito_sans.className} antialiased w-screen h-screen overflow-hidden`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="p-4 w-screen h-screen relative">
            <AppTitle />
            <div className="w-full h-full">
              {children}
            </div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
